"""Live/paper-trading risk layer: the full TDD Part 8 limit set.

Composes the Phase-1 ``RiskEngine`` (per-order veto, unchanged — the
backtester keeps using it directly) with the controls that only make
sense in a running session:

  Tiered drawdown response   NORMAL -> HALVED (soft dd) -> FLATTEN (hard
                             dd) -> HALTED (breaker); each tier is strictly
                             more restrictive, and HALTED requires a manual
                             ``reset()`` — the TDD's "manual override
                             required to resume".
  Circuit breakers           trip on N consecutive risk rejections, stale
                             market data, broker error spike, or the
                             manual panic button.
  Volatility targeting       target weights are scaled down as realized
                             portfolio vol exceeds the target band.

The layering rule: this class may only make the book SMALLER than the
raw strategy asked for. The absolute veto still belongs to RiskEngine —
every order, including exits generated by FLATTEN, transits it.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

import numpy as np

from .engine import Order, PortfolioState, RiskDecision, RiskEngine
from .limits import RiskLimits

TRADING_DAYS = 252


class RiskTier(str, Enum):
    NORMAL = "NORMAL"
    HALVED = "HALVED"          # soft drawdown breached: new risk sized x0.5
    FLATTEN = "FLATTEN"        # hard drawdown breached: exits only
    HALTED = "HALTED"          # circuit breaker tripped: manual reset required


@dataclass
class BreakerStatus:
    tripped: bool = False
    reason: str | None = None


class LiveRiskManager:
    def __init__(self, limits: RiskLimits | None = None):
        self.limits = limits or RiskLimits()
        self.engine = RiskEngine(self.limits)
        self.breaker = BreakerStatus()
        self._consecutive_rejects = 0

    # ------------------------------------------------------------------
    # Tier / sizing
    # ------------------------------------------------------------------
    def tier(self, state: PortfolioState) -> RiskTier:
        if self.breaker.tripped:
            return RiskTier.HALTED
        dd = 1.0 - state.equity / state.peak_equity if state.peak_equity > 0 else 0.0
        if dd > self.limits.flatten_drawdown:
            return RiskTier.FLATTEN
        if dd > self.limits.soft_drawdown:
            return RiskTier.HALVED
        return RiskTier.NORMAL

    def size_factor(self, state: PortfolioState) -> float:
        """Multiplier applied to NEW target risk before orders are built."""
        t = self.tier(state)
        if t == RiskTier.NORMAL:
            return 1.0
        if t == RiskTier.HALVED:
            return 0.5
        return 0.0                                    # FLATTEN / HALTED

    def vol_scale(self, daily_returns) -> float:
        """Volatility-targeting multiplier from recent realized returns."""
        r = np.asarray(daily_returns, dtype=float)
        r = r[~np.isnan(r)]
        if len(r) < 21:
            return 1.0
        realized = r[-63:].std() * np.sqrt(TRADING_DAYS)
        if realized <= self.limits.target_vol or realized == 0:
            return 1.0
        return max(self.limits.target_vol / realized, self.limits.vol_scale_floor)

    # ------------------------------------------------------------------
    # Per-order gate (delegates the veto, layers the breakers)
    # ------------------------------------------------------------------
    def evaluate(self, order: Order, state: PortfolioState) -> RiskDecision:
        if self.breaker.tripped:
            decision = RiskDecision(
                order_id=order.order_id, ts=order.ts, symbol=order.symbol,
                side=order.side, notional=order.notional, outcome="REJECT",
                breached_rule=f"circuit_breaker:{self.breaker.reason}",
                limit_snapshot=self.limits.snapshot(),
            )
            self.engine.decisions.append(decision)
            return decision

        tier = self.tier(state)
        if tier == RiskTier.FLATTEN and order.side == "BUY":
            decision = RiskDecision(
                order_id=order.order_id, ts=order.ts, symbol=order.symbol,
                side=order.side, notional=order.notional, outcome="REJECT",
                breached_rule="flatten_tier_active",
                limit_snapshot=self.limits.snapshot(),
            )
            self.engine.decisions.append(decision)
            return decision

        decision = self.engine.evaluate(order, state)

        if decision.approved:
            self._consecutive_rejects = 0
        else:
            self._consecutive_rejects += 1
            if self._consecutive_rejects >= self.limits.breaker_consecutive_rejects:
                self.trip(f"{self._consecutive_rejects} consecutive risk rejections")
        return decision

    # ------------------------------------------------------------------
    # Breakers
    # ------------------------------------------------------------------
    def trip(self, reason: str) -> None:
        self.breaker = BreakerStatus(tripped=True, reason=reason)

    def panic(self) -> None:
        """Manual kill switch (TDD: manual panic button)."""
        self.trip("manual_panic")

    def on_feed_staleness(self, seconds_silent: float) -> None:
        if seconds_silent > self.limits.breaker_feed_stale_secs:
            self.trip(f"market data stale {seconds_silent:.0f}s")

    def on_broker_errors(self, error_count: int, window: int = 10) -> None:
        if error_count >= max(window // 2, 3):
            self.trip(f"broker API error spike ({error_count} errors)")

    def reset(self) -> None:
        """Manual re-arm after a halt. Deliberately NOT automatic."""
        self.breaker = BreakerStatus()
        self._consecutive_rejects = 0

    # ------------------------------------------------------------------
    def status(self) -> dict:
        return {
            "breaker_tripped": self.breaker.tripped,
            "breaker_reason": self.breaker.reason,
            "consecutive_rejects": self._consecutive_rejects,
        }

    def decisions_frame(self):
        return self.engine.decisions_frame()
